'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Elektraostog_Solaryl.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;fr&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''    &lt;title&gt;À propos d&apos;Elektraostog Solaryl&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: &quot;Segoe UI&quot;, Arial, sans-serif;
        '''            background: linear-gradient(135deg, #0f056b, #0044ff);
        '''            background-attachment: fixed;
        '''            color: #ffffff;
        '''            display: flex;
        '''            flex-direction: column;
        '''            align-item [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property about() As String
            Get
                Return ResourceManager.GetString("about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exit_clair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit_clair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Favoris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Favoris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Favoris_clair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Favoris_clair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;fr&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''    &lt;title&gt;Historique&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: &quot;Segoe UI&quot;, Arial, sans-serif;
        '''            background: linear-gradient(135deg, #0f056b, #0044ff);
        '''            background-attachment: fixed;
        '''            color: #ffffff;
        '''            display: flex;
        '''            flex-direction: column;
        '''            align-items: center;
        '''          [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property history() As String
            Get
                Return ResourceManager.GetString("history", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Max() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Max", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Max_clair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Max_clair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Min_clair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Min_clair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Minn_clair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minn_clair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NAbout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NAbout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NAddFavorite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NAddFavorite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NClosePage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NClosePage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NDevTools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NDevTools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NDiscord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NDiscord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NExit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NExit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NFavoris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NFavoris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NForwards() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NForwards", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NHistory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NHistory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NInstagram() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NInstagram", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NMax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NMax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NMin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NMin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NMinn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NMinn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NNewPage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NNewPage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;fr&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''    &lt;title&gt;Erreur 404 - Page introuvable&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: &quot;Segoe UI&quot;, Arial, sans-serif;
        '''            background: linear-gradient(135deg, #0f056b, #0044ff);
        '''            background-attachment: fixed;
        '''            color: #ffffff;
        '''            display: flex;
        '''            flex-direction: column;
        '''            align-items: [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property notfound() As String
            Get
                Return ResourceManager.GetString("notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NPage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NPage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NRefresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NRefresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NSolarys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NSolarys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NUpdate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NUpdate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NWebSite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NWebSite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NY_Aller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NY_Aller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NYouTube() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NYouTube", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_clair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_clair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_sombre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_sombre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;fr&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''    &lt;title&gt;Paramètres du navigateur&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: &quot;Segoe UI&quot;, Arial, sans-serif;
        '''            background: linear-gradient(135deg, #0f056b, #0044ff);
        '''            background-attachment: fixed;
        '''            color: #ffffff;
        '''            display: flex;
        '''            flex-direction: column;
        '''            align-items: cent [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property settings() As String
            Get
                Return ResourceManager.GetString("settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;fr&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''    &lt;title&gt;Mise à jour du navigateur&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: &quot;Segoe UI&quot;, Arial, sans-serif;
        '''            background: linear-gradient(135deg, #0f056b, #0044ff);
        '''            background-attachment: fixed;
        '''            color: #ffffff;
        '''            display: flex;
        '''            flex-direction: column;
        '''            align-items: cen [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property update() As String
            Get
                Return ResourceManager.GetString("update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y_aller_clair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y_aller_clair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y_aller_sombre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y_aller_sombre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
